FROM debian:buster

RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
RUN echo 'man-db man-db/auto-update boolean false' | debconf-set-selections
RUN set -ex \
    && apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends \
               build-essential \
               cdbs \
               devscripts \
               equivs \
               fakeroot \
    && apt-mark minimize-manual -y \
    && apt-get autopurge -y \
    && apt-get clean
RUN rm -rf /tmp/* /var/tmp/*
