FROM debian:bullseye

RUN sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list
RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               cdbs \
               devscripts \
               equivs \
               fakeroot \
    && apt-get clean
RUN rm -rf /tmp/* /var/tmp/*
